# Site settings
course_name: LING 351 Language Technology and Large Language Models
course_description: This course explores the interaction between language and technology, from the invention of writing systems to modern tools that process and generate language using large language models. While not a technical course in natural language processing (NLP), it may serve as a potential gateway to more implementation-focused studies, as students will learn basic text processing skills in Python. The primary focus is on the linguistic and conceptual understanding underlying language technologies.
course_semester: "Fall 2025"

baseurl: "/LING351-LT" # the subpath of your site, e.g. /blog/
url: "http://hksung-tch.github.io/" # the base hostname & protocol for your site

schoolname: "RIT"
#schoolurl: "https://www.rit.edu/liberalarts/"

address: |
    Hakyung Sung (hksgla@rit.edu)
    Department of Psychology, College of liberal arts

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
